# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 03:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_auto_20170605_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 6, 6, 50, 51, 917047), verbose_name='Update Date'),
        ),
    ]
