# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('imei', models.CharField(max_length=30)),
                ('phone_num', models.CharField(max_length=30)),
                ('purchase_date', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('assigned_to', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
            options={
                'verbose_name': 'GPSDevice',
                'verbose_name_plural': 'GPSDevices',
                'ordering': ['purchase_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='gpsdevice',
            unique_together=set([('name', 'imei', 'phone_num')]),
        ),
    ]
