# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 08:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_num', models.CharField(default=None, max_length=30, verbose_name='Licence Number')),
                ('type', models.CharField(default=None, max_length=30, verbose_name='Type')),
                ('engine_num', models.CharField(default=None, max_length=30, verbose_name='Engin Number')),
                ('registration_date', models.DateField(default=None, null=True, verbose_name='Registration Date')),
                ('number_of_seats', models.CharField(default=None, max_length=30, verbose_name='Number of Seats')),
                ('color', models.CharField(default=None, max_length=30, verbose_name='Color')),
                ('make', models.CharField(default=None, max_length=30, verbose_name='make')),
                ('model', models.CharField(default=None, max_length=30, verbose_name='Model')),
                ('year', models.CharField(default=None, max_length=30, verbose_name='Year')),
                ('body_type', models.CharField(default=None, max_length=30, verbose_name='Body Type')),
                ('gas_type', models.CharField(default=None, max_length=30, verbose_name='Gas Type')),
                ('date_of_purchase', models.DateField(default=None, max_length=30, verbose_name='Date of Purchase')),
                ('km_read_at_purchase', models.IntegerField(default=None, verbose_name='Km Read at Purchase')),
                ('licence_renewal_date', models.DateField(default=None, max_length=30, verbose_name='Licence Renewal Date')),
                ('insurance_renewal_date', models.DateField(default=None, max_length=30, verbose_name='Insurance Renewal Date')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['licence_num'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(default=datetime.datetime.today)),
                ('end_date', models.DateField(null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, verbose_name='Status')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
    ]
