# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_num', models.CharField(max_length=9, unique=True)),
                ('model', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('color', models.CharField(default='white', max_length=20)),
                ('production_year', models.CharField(max_length=20)),
                ('date_of_purchase', models.DateField()),
                ('km_read_at_purchase', models.IntegerField()),
                ('license_renewal_date', models.DateField()),
                ('insurance_renewal_date', models.DateField()),
                ('current_driver', models.CharField(max_length=30)),
                ('status', models.CharField(default='active', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('driver', models.CharField(max_length=20)),
                ('start_date', models.DateField(default=datetime.datetime.today)),
                ('end_date', models.DateField(null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
    ]
