# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20170606_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyrecord',
            name='month',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='monthlyrecord',
            name='year',
            field=models.CharField(max_length=30),
        ),
    ]
