# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_auto_20170606_0659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyrecord',
            options={'ordering': ['vehicle']},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyrecord',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='monthlyrecord',
            name='month',
        ),
        migrations.RemoveField(
            model_name='monthlyrecord',
            name='year',
        ),
    ]
