# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_auto_20170606_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyrecord',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='MonthlyRecord',
        ),
    ]
