# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 08:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(blank=True, max_length=50, null=True)),
                ('driver', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(default=datetime.datetime(2017, 6, 5, 11, 1, 15, 125805))),
                ('cost', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
