# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 09:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 23, 12, 57, 6, 380095)),
        ),
    ]
