# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 08:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0002_auto_20170605_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 5, 11, 20, 55, 829747)),
        ),
    ]
