# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 04:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0013_auto_20170606_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='date',
        ),
        migrations.AddField(
            model_name='accident',
            name='date_of_accident',
            field=models.DateField(default=datetime.datetime(2017, 6, 6, 7, 51, 29, 139740)),
        ),
        migrations.AddField(
            model_name='accident',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Driver'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='image',
            field=models.ImageField(blank=True, default='accidents/no_image.png', upload_to='accidents/'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle'),
        ),
    ]
